### ISSUE TITLE
Handling usage

### ISSUE THREAD

**Issue by tonypartridger** [AllanGallop/laravel-xero-oauth2-multi-tenant#1]
This looks promising, we have a single login for XERO which handles the majority of our clients so we would connect to it and approve the tenants. At the moment I store the tenant ID against the client model so we can then only get that clients tenant information.

How are you handling individual tenant data calls opposed to just storing the tenants? For example, I have a custom version of dcbloggers XERO API which I added a custom function to setTenantId then all subsequent API Calls use the set Tenant ID. It's working ok for now for my use case but not perfect.

**Comment by AllanGallop** [comment]
For own use, we use this libary in a Lumen microservice that handles all things Xero. Pretty simple setup with a custom storage service that binds to the specific user on our Auth service. We then request an object of currently connected tenants, present to UI for user selection and in any formal action request to Xero the correct TenantID is then passed as a route parameter.

This fork effectively lets us query currently connected tenants via getTenants() and specify which Tenant to use, due to stateless nature of the service it's utilised with a tenant must be specified for each request. On the frontend the choice is made via a select dropdown.
